version: "3.9"
services:    
  backend:
    build: ./pi-coursework-server
    container_name: backend
    restart: always
    environment:
      BACKEND_PORT: 8080
    ports:
      - "8080:8080"
    # volumes:
      # - ./volumes/backend/static:/app-server/static
    

volumes:
  backend: